name: Sync Labels

on:
  workflow_dispatch:
    inputs:
      mode:
        description: "Run mode"
        required: true
        default: "dry-run"
        type: choice
        options:
          - dry-run
          - real
          - purge-only

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_PAT }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Run label updater
        run: |
          RED='\033[0;31m'
          NC='\033[0m'
          MODE=${{ github.event.inputs.mode }}
          if [ "$MODE" = "purge-only" ]; then
            echo -e "${RED}🚨🚨🚨 PURGE-ONLY MODE ACTIVE 🚨🚨🚨${NC}"
            echo -e "${RED}All non-whitelisted labels will be deleted. No labels will be created or updated.${NC}"
          else
            echo "Running label updater in $MODE mode..."
          fi
          python github-label-updater/setup_labels.py $MODE $GITHUB_TOKEN
