name: Sync Labels

on:
  workflow_dispatch:
    inputs:
      mode:
        description: "Run mode: dry-run or real"
        required: true
        default: "dry-run"
        type: choice
        options:
          - dry-run
          - real
  push:
    paths:
      - "github-label-updater/labels_data.py"
      - "github-label-updater/repos_data.py"
      - ".github/workflows/sync-labels.yml"

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_PAT }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Run label updater
        run: |
          echo "Running label updater in ${{ github.event.inputs.mode }} mode..."
          
          # Enable dry-run if mode is dry-run
          if [ "${{ github.event.inputs.mode }}" = "dry-run" ]; then
            sed -i 's/DRY_RUN = False/DRY_RUN = True/' github-label-updater/setup_labels.py
          else
            sed -i 's/DRY_RUN = True/DRY_RUN = False/' github-label-updater/setup_labels.py
          fi

          python github-label-updater/setup_labels.py
