name: Sync Labels

on:
  workflow_dispatch:
    inputs:
      mode:
        description: "Run mode"
        required: true
        default: "dry-run"
        type: choice
        options:
          - dry-run
          - real
          - purge-only

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_PAT }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Run label updater
        run: |
          MODE=${{ github.event.inputs.mode }}
          echo "Running label updater in $MODE mode..."
          python github-label-updater/setup_labels.py $MODE $GITHUB_TOKEN
